set(ENABLE_PROTECTION TRUE)
add_compile_definitions(ENABLE_PROTECTION=1)

set(CRASH_ON_CORRUPTION FALSE)

set(PROTECTION_DEBUG FALSE)

set(ENABLE_STATISTIC FALSE)

set(CONFIG_ENABLED_OPTIONS ENABLE_PROTECTION)
