set(ENABLE_PROTECTION TRUE)
add_compile_definitions(ENABLE_PROTECTION=1)

set(CRASH_ON_CORRUPTION TRUE)
add_compile_definitions(CRASH_ON_CORRUPTION=1)

set(PROTECTION_DEBUG TRUE)
add_compile_definitions(PROTECTION_DEBUG=1)

set(ENABLE_STATISTIC TRUE)
add_compile_definitions(ENABLE_STATISTIC=1)

set(ENABLE_ERROR_REPORT TRUE)
add_compile_definitions(ENABLE_ERROR_REPORT=1)

set(CONFIG_ENABLED_OPTIONS ENABLE_PROTECTION CRASH_ON_CORRUPTION PROTECTION_DEBUG ENABLE_STATISTIC ENABLE_ERROR_REPORT)
