set(ENABLE_PROTECTION TRUE)
add_compile_definitions(ENABLE_PROTECTION=1)

set(CRASH_ON_CORRUPTION TRUE)
add_compile_definitions(CRASH_ON_CORRUPTION=1)

set(PROTECTION_DEBUG FALSE)

set(ENABLE_STATISTIC FALSE)

set(CONFIG_ENABLED_OPTIONS ENABLE_PROTECTION CRASH_ON_CORRUPTION)
